config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :customers
  resources :components
  resources :comp_arrays

  resources :charts, only: [] do
    collection do
      get 'all_comp_arrays'
    end
  end

  resources :user_options, only: [:create]

end

app/models/customer.rb
class Customer < ApplicationRecord

  include Graphable

  has_many :comp_arrays
  has_many :components, through: :comp_arrays

  alias_attribute :description, :name

  def start_date
    comp_arrays.minimum(:install_date) || Date.today
  end

  def total_value_at_date(date)
    comp_arrays.inject(0) { |n, ca| n + ca.total_value_at_date(date) }
  end

  def flagged?
    comp_arrays.any?(&:flagged?)
  end

  def flagged_reason
    "Depreciating soon: #{
      comp_arrays.select(&:flagged?).map(&:serial_number).to_sentence}"
  end

  def total_initial_value_at_date(date)
    comp_arrays.map { |ca| ca.total_initial_value_at_date(date) }.sum
  end

  def percent_at_date(date)
    total_value_at_date(date) / total_initial_value_at_date(date).to_f
  end

  def depreciated_or_flagged?
    flagged?
  end

  def depreciated?
    false
  end

  def other_reason
    ''
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customers.html.haml
= line_chart_with customers.map(&:graph_info)
= render "customers/table", customers: customers

app/views/customers/_form.html.haml
= form_for(customer) do |f|
  - if customer.errors.any?
    #error_explanation
      %h2
        = pluralize(customer.errors.count, "error")
        prohibited this customer from being saved:
      %ul
        - customer.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save', class: 'btn btn-primary'
    = link_to 'Back', customers_path, class: 'btn btn-secondary'

app/views/customers/_table.html.haml
%table.table.tablesorter.tablesorter-default
  %thead
    %tr
      %th Name
      %th Current Value
      %th Arrays
      %th Components
      %th{'data-sorter'=>'false', 'data-filter'=>'false'}
      %th{:colspan => '2', 'data-sorter'=>'false', 'data-filter'=>'false'}
  %tbody
    - customers.each do |customer|
      %tr
        %td= link_to customer.name, customer
        %td= number_to_currency(customer.total_value_at_date(Date.today))
        %td= customer.comp_arrays.count
        %td= customer.components.count
        %td= renewal_flag(customer)
        %td
          .btn-group.btn-group-sm
            %button.btn.btn-secondary.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
              Action
            .dropdown-menu
              = link_to 'Show', customer, class: 'dropdown-item'
              = link_to 'Edit', edit_customer_path(customer), class: 'dropdown-item'
              .dropdown-divider
              = link_to 'Delete', customer, method: :delete, data: { confirm: 'Are you sure?' }, class: 'dropdown-item'

app/views/customers/edit.html.haml
%h1 Editing Customer
= render 'form', customer: @customer

app/views/customers/index.html.haml
%p#notice= notice
%h1 Customers

= render 'customers', customers: @customers

= link_to 'New Customer', new_customer_path, class: 'btn btn-primary'

app/views/customers/new.html.haml
%h1 New Customer
= render 'form', customer: @customer

app/views/customers/show.html.haml
%p#notice= notice
%h1 Customer

= render 'customers', customers: [@customer]

%h3 Arrays

= render 'comp_arrays/comp_arrays', comp_arrays: @customer.comp_arrays

= link_to 'New Array',
new_comp_array_path(comp_array: { customer_id: @customer }),
class: 'btn btn-primary'

%h3 Components

= render 'components/components', components: @customer.components

= link_to 'New Component',
new_component_path(component: { customer_id: @customer }),
class: 'btn btn-primary'