config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :customers
  resources :components
  resources :comp_arrays

  resources :charts, only: [] do
    collection do
      get 'all_comp_arrays'
    end
  end

  resources :user_options, only: [:create]

end

app/models/comp_array.rb
class CompArray < ApplicationRecord

  include Depreciable
  include Graphable
  include ActionView::Helpers::DateHelper # Use time_ago_in_words
  include ActionView::Helpers::TextHelper # Use pluralize

  has_many :components
  belongs_to :customer

  alias_attribute :start_date, :install_date

  def value_of_components_at_date(date)
    components.inject(0) { |a, e| a + e.value_at_date(date) }
  end

  def current_value_of_components
    value_of_components_at_date(Date.today)
  end

  def total_value_at_date(date)
    value_at_date(date) + value_of_components_at_date(date)
  end

  def total_current_value
    total_value_at_date(Date.today)
  end

  def flagged?
    near_depreciation || components.any?(&:flagged?)
  end

  def flagged_reason
    return '' unless near_depreciation
    "Completely depreciates in #{time_ago_in_words(start_date + 3.years)}. "
  end

  def other_reason
    return '' unless components.any?(&:depreciated_or_flagged?)
    r = ''
    if components.any?(&:depreciated?)
      r += "#{pluralize(components.select(&:depreciated?).count, 'component')
        } depreciated. "
    end
    if components.any?(&:flagged?)
      r += "#{pluralize(components.select(&:flagged?).count, 'component')
        } depreciating soon."
    end
    r
  end

  def total_initial_value_at_date(date)
    return 0 if date < install_date
    initial_value +
      components.where('install_date <= ?', date).pluck(:initial_value).sum
  end

  def percent_at_date(date)
    total_value_at_date(date) / total_initial_value_at_date(date).to_f
  end

end

app/controllers/comp_arrays_controller.rb
class CompArraysController < ApplicationController
  before_action :set_comp_array, only: [:show, :edit, :update, :destroy]

  # GET /comp_arrays
  # GET /comp_arrays.json
  def index
    @comp_arrays = CompArray.all.includes(:customer, :components)
  end

  # GET /comp_arrays/1
  # GET /comp_arrays/1.json
  def show
  end

  # GET /comp_arrays/new
  def new
    @comp_array = CompArray.new(comp_array_params)
  end

  # GET /comp_arrays/1/edit
  def edit
  end

  # POST /comp_arrays
  # POST /comp_arrays.json
  def create
    @comp_array = CompArray.new(comp_array_params)

    respond_to do |format|
      if @comp_array.save
        format.html { redirect_to @comp_array, notice: 'Array was successfully created.' }
        format.json { render :show, status: :created, location: @comp_array }
      else
        format.html { render :new }
        format.json { render json: @comp_array.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comp_arrays/1
  # PATCH/PUT /comp_arrays/1.json
  def update
    respond_to do |format|
      if @comp_array.update(comp_array_params)
        format.html { redirect_to @comp_array, notice: 'Array was successfully updated.' }
        format.json { render :show, status: :ok, location: @comp_array }
      else
        format.html { render :edit }
        format.json { render json: @comp_array.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comp_arrays/1
  # DELETE /comp_arrays/1.json
  def destroy
    @comp_array.destroy
    respond_to do |format|
      format.html { redirect_to comp_arrays_url, notice: 'Array was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comp_array
      @comp_array = CompArray.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comp_array_params
      params.fetch(:comp_array, {}).permit(:description, :install_date, :initial_value, :location, :customer_id, :serial_number)
    end
end

app/helpers/comp_arrays_helper.rb
module CompArraysHelper
end

app/views/comp_arrays/_comp_arrays.html.haml
= line_chart_with comp_arrays.map(&:graph_info)
= render "comp_arrays/table", comp_arrays: comp_arrays

app/views/comp_arrays/_form.html.haml
= form_for(comp_array) do |f|
  - if comp_array.errors.any?
    #error_explanation
      %h2
        = pluralize(comp_array.errors.count, "error")
        prohibited this comp_array from being saved:
      %ul
        - comp_array.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :serial_number
    = f.text_field :serial_number
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :install_date
    = f.date_select :install_date
  .field
    = f.label :initial_value
    = f.number_field :initial_value, step: 0.01, in: (0.01..999_999_999.99)
  .field
    = f.label :location
    = f.text_field :location
  .field
    = f.label :customer_id
    = collection_select(:comp_array, :customer_id, Customer.all, :id, :name)
  .actions
    = f.submit 'Save', class: 'btn btn-primary'
    = link_to 'Back', comp_arrays_path, class: 'btn btn-secondary'

app/views/comp_arrays/_table.html.haml
%table.table.tablesorter.tablesorter-default
  %thead
    %tr
      %th Serial Number
      %th Description
      %th Location
      %th Customer
      %th Install date
      %th Initial value
      %th Current Value
      %th Comp. Current Value
      %th Total Current Value
      %th{:colspan => '2', 'data-sorter'=>'false', 'data-filter'=>'false'}
  %tbody
    - comp_arrays.each do |comp_array|
      %tr
        %td= link_to comp_array.serial_number, comp_array
        %td= comp_array.description
        %td= comp_array.location
        %td= link_to comp_array.customer.name, comp_array.customer
        %td= comp_array.install_date
        %td= number_to_currency(comp_array.initial_value)
        %td= number_to_currency(comp_array.current_value.round(2))
        %td= number_to_currency(comp_array.current_value_of_components.round(2))
        %td= number_to_currency(comp_array.total_current_value.round(2))
        %td= renewal_flag(comp_array)
        %td
          .btn-group.btn-group-sm
            %button.btn.btn-secondary.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
              Action
            .dropdown-menu
              = link_to 'Show', comp_array, class: 'dropdown-item'
              = link_to 'Edit', edit_comp_array_path(comp_array), class: 'dropdown-item'
              .dropdown-divider
              = link_to 'Delete', comp_array, method: :delete, data: { confirm: 'Are you sure?' }, class: 'dropdown-item'

app/views/comp_arrays/edit.html.haml
%h1 Editing Array
= render 'form', comp_array: @comp_array

app/views/comp_arrays/index.html.haml
%p#notice= notice
%h1 Arrays

= render 'comp_arrays', comp_arrays: @comp_arrays

= link_to 'New Array', new_comp_array_path, class: 'btn btn-primary'

app/views/comp_arrays/new.html.haml
%h1 New Array
= render 'form', comp_array: @comp_array

app/views/comp_arrays/show.html.haml
%p#notice= notice

%h1 Array #{@comp_array.serial_number}

= render 'comp_arrays', comp_arrays: [@comp_array]

%h3 Components

= render '/components/components', components: @comp_array.components

= link_to 'New Component',
new_component_path(component: { comp_array_id: @comp_array }),
class: 'btn btn-primary'