config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :customers
  resources :components
  resources :comp_arrays

  resources :charts, only: [] do
    collection do
      get 'all_comp_arrays'
    end
  end

  resources :user_options, only: [:create]

end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    / Required meta tags always come first
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    %meta{:content => "ie=edge", "http-equiv" => "x-ua-compatible"}/
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/

    %title Arraycomp
    / Bootstrap CSS
    %link{:crossorigin => "anonymous", :href => "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/css/bootstrap.min.css", :integrity => "2hfp1SzUoho7/TsGGGDaFdsuuDL0LX2hnUp6VkX3CUQ2K4K+xjboZdsXyp4oUHZj", :rel => "stylesheet"}/
    = csrf_meta_tags
    = javascript_include_tag '//www.google.com/jsapi'
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    %nav.navbar.navbar-light.bg-faded
      %button.navbar-toggler.hidden-sm-up{"aria-controls" => "array_comp_navbar", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#array_comp_navbar", "data-toggle" => "collapse", :type => "button"}
        \☰
      #array_comp_navbar.collapse.navbar-toggleable-xs
        = link_to 'ArrayComp', root_path, class: "navbar-brand #{controller_name == 'home' ? '' : 'text-muted'}"
        %ul.nav.navbar-nav
          %li.nav-item{class: controller_name == 'comp_arrays' ? 'active' : ''}
            = link_to 'Arrays', comp_arrays_path, class: 'nav-link'
          %li.nav-item{class: controller_name == 'components' ? 'active' : ''}
            = link_to 'Components', components_path, class: 'nav-link'
          %li.nav-item{class: controller_name == 'customers' ? 'active' : ''}
            = link_to 'Customers', customers_path, class: 'nav-link'
          %li.nav-item
            %a.nav-link{"data-target" => "#myModal", "data-toggle" => 'modal', :href => "#"} Options

    #myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
      .modal-dialog{:role => "document"}
        .modal-content
          .modal-header
            %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
              %span{"aria-hidden" => "true"} ×
            %h4#myModalLabel.modal-title Options
          = form_for(user_options, url: user_options_path) do |f|
            .modal-body
              .field
                = f.label :flag_at_months
                = f.text_field :flag_at_months
              .field
                = f.label :show_percent_graphs
                = f.check_box :show_percent_graphs
            .modal-footer
              %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Close
              = f.submit('Save changes', class: 'btn btn-primary')

    .body_center= yield

    %br